const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Behaviors.destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Direcao_Dash: 0},
	{Ativo_Dash: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Projétil: 0},
	{Flash: 0},
	{PersonagemPrincipal: 0},
	{Teclado: 0},
	{Áudio: 0},
	{Mosaico: 0},
	{Sólido: 0},
	{PisoInvisivel: 0},
	{Direcao: 0},
	{Piscar: 0},
	{monstro: 0},
	{direita: 0},
	{esquerda: 0},
	{Coracao: 0},
	{AreaDano: 0},
	{GameOverBack: 0},
	{Mouse: 0},
	{GameOverFont: 0},
	{FontMenu: 0},
	{FontRestart: 0},
	{MenuBack: 0},
	{MenuFont: 0},
	{StartFont: 0},
	{Mosaico2: 0},
	{boss: 0},
	{sensor: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{win: 0},
	{SpriteFont: 0},
	{Vidas: 0},
	{vidaboss: 0}
];

self.InstanceType = {
	PersonagemPrincipal: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	PisoInvisivel: class extends self.ISpriteInstance {},
	monstro: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	Coracao: class extends self.ISpriteInstance {},
	AreaDano: class extends self.ISpriteInstance {},
	GameOverBack: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	FontMenu: class extends self.ISpriteFontInstance {},
	FontRestart: class extends self.ISpriteFontInstance {},
	MenuBack: class extends self.ITiledBackgroundInstance {},
	MenuFont: class extends self.ISpriteFontInstance {},
	StartFont: class extends self.ISpriteFontInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	boss: class extends self.ISpriteInstance {},
	sensor: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	win: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {}
}